### ISSUE TITLE
Exception in TCA on new install with TYPO3 v12 and pluswerk/mail-logger (due to not using associative keys for items of field "module" in TCA pages.php)

### ISSUE THREAD

**Issue by sypets** [in2code-de/publications#78]
## Description

`> @php vendor/bin/typo3 extension:setup`

```
Uncaught TYPO3 Exception #1476107295: PHP Warning: Undefined array key "value" 
in /var/www/site-uol12/vendor/in2code/publications/Configuration/TCA/Overrides/pages.php line 12
thrown in file /var/www/site-uol12/vendor/typo3/cms-core/Classes/Error/ErrorHandler.php
in line 141

```

vendor/in2code/publications/Configuration/TCA/Overrides/pages.php

```
11 foreach ($GLOBALS['TCA']['pages']['columns']['module']['config']['items'] as $item) {
12    if ($item['value'] === $ext) {
```

https://github.com/in2code-de/publications/blob/53265d090bcb48bec704c9e72b4f9f64ca0790a3/Configuration/TCA/Overrides/pages.php#L12

## Reason for problem

in2code/publications assumes associative array key 'value' in `$GLOBALS['TCA']['pages']['columns']['module']['config']['items']['*']` but they may not exist as TYPO3 added associative array keys for TCA items in TYPO3 v12, but they are not yet mandatory:

https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.3/Feature-99739-AssociativeArrayKeysForTCAItems.html

## Reproduce

On TYPO3 v12 system add in2code/publications and pluswerk/mail-logger:

1. Install publications and mail-logger:

```
composer require in2code/publications
composer require pluswerk/mail-logger:dev-master
```

2. Run post-install commands:

```
php vendor/bin/typo3 extension:setup
php vendor/bin/typo3 database:updateschema
php vendor/bin/typo3 cache:flush
...

```

## Versions

* TYPO3: 12.4.36
* publications:  6.2.1
* pluswerk/mail-logger: dev-master
* PHP: 8.3.6
* composer installation: yes

## Additional context

We can't really change this in mail_logger, because it still supports v11 in main branch. Also, the same problem might occur with other extensions.

**Comment by sebastianstein** [comment]
fixed in the typo3-v12 branch

**Comment by tobiasschaeferptb** [comment]
Hello,

I have still an error after updating from 6.1.0 to 6.2.3:
PHP Warning: Undefined array key 1 in /vendor/in2code/publications/Configuration/TCA/Overrides/pages.php line 12
Changing line 12 from:
if ($item['1'] == $ext || $item['value'] === $ext) {
to:
if ($item['1'] ?? '' == $ext || $item['value'] ?? '' === $ext) {
solves it.
I also was wondering why there is a == used in the first condition and a === in the second. It should be the same.

Greetings,
Tobias Schäfer
